services:
  www:
    build:
      context: .
    image: php:8.3-apache
    volumes:
      - ./app:/var/www/html
      - ./resources/config.inc.php:/var/www/html/config/config.inc.php
    ports:
      - 8080:80
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=oai-pmh
    volumes:
      - ./resources/db:/docker-entrypoint-initdb.d

